static const char *docs_usage[] = {
"usage epd [-k|--key <file>] [-d|--database <file>]",
"          [-v|--version] [-h|--help]",
"          <command> [args]",
"",
"Commands (unique prefixes accepted):",
"",
"k means the global argument <key> is required",
"d means the global argument <database> is required",
"",
"  [  ] keygen <file name>      generate new key",
"  [k ] create <database name>  create new database",
"  [kd] list                    list the entry of the database",
"  [kd] add [-e <entry name>]   add a entry to database",
"           [-n <note>]         specify name, note, tags",
"           [-t <tags>]         the key can be specified for additional",
"           [-k <key>]          encryption",
"  [kd] delete <keyword/htag>   delete entry(s) searching by keyword",
"                               of the name or htag",
"  [kd] search <keyword>        search the entry using keyword",
"  [kd] show [-k key]           show the designated field of the",
"            [name/entry]       entry, specified by the htag", 
"            [note]             the key may be required if value",
"            [value]            is the sub-command",
"            <htag>             ",
"  --version                    display version information",
"  --help                       display this usage information",
"",
"EPD (Encrypted Password Database) is a encrypted database that keeps", 
"your password safe it uses ChaCha20, and HMAC-SHA256.",
"",
"Author: lewisxy",
0};
